package com.ikokoon.serenity.applet;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.net.URL;

import com.ikokoon.serenity.model.IModel;
import com.ikokoon.toolkit.Base64;

public class ModelGrabber {

	protected IModel getModel(URL documentBase, String uri) {
		try {
			URL url = new URL(documentBase, uri);
			InputStream inputStream = url.openStream();
			String base64 = getContents(inputStream).toString();
			return (IModel) deserializeFromBase64(base64);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}

	/**
	 * De-serializes an object from a base 64 string to an object.
	 * 
	 * @param base64
	 *            the base 64 string representation of the object
	 * @return the object de-serialised from the string or null if an exception is thrown
	 */
	private Object deserializeFromBase64(String base64) {
		byte[] bytes = Base64.decode(base64);
		ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(bytes);
		try {
			ObjectInputStream objectInputStream = new ObjectInputStream(byteArrayInputStream);
			return objectInputStream.readObject();
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}

	/**
	 * Reads the contents of the file and returns the contents in a byte array form.
	 * 
	 * @param inputStream
	 *            the file to read the contents from
	 * @return the file contents in a byte array output stream
	 * @throws Exception
	 */
	private ByteArrayOutputStream getContents(InputStream inputStream) {
		ByteArrayOutputStream bos = new ByteArrayOutputStream();
		if (inputStream == null) {
			return bos;
		}
		try {
			byte[] bytes = new byte[1024];
			int read;
			while ((read = inputStream.read(bytes)) > -1) {
				bos.write(bytes, 0, read);
			}
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			try {
				inputStream.close();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		return bos;
	}

	protected static String projectBase64 = "rO0ABXNyACBjb20uaWtva29vbi5zZXJlbml0eS5tb2RlbC5Nb2RlbGSMpEB/c+h5AgAETAAGbGVnZW5kdAAQTGphdmEvdXRpbC9MaXN0O0wABmxpbWl0c3EAfgABTAAHbWV0cmljc3EAfgABTAAEbmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO3hwc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNpemV4cAAAAAl3BAAAAAp0AApDb3ZlcmFnZSAldAAKQ29tcGxleGl0eXQADkFic3RyYWN0IDwgMS4wdAAPU3RhYmlsaXR5IDwgMS4wdAAORGlzdGFuY2UgPCAxLjB0AAVMaW5lc3QAB01ldGhvZHN0AAdDbGFzc2VzdAAIUGFja2FnZXN4c3EAfgAEAAAACXcEAAAACnNxAH4ABAAAAAR3BAAAAApzcgAQamF2YS5sYW5nLkRvdWJsZYCzwkopa/sEAgABRAAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHBASQAAAAAAAHNxAH4AEUA+AAAAAAAAc3EAfgARQCQAAAAAAABzcQB+ABE/8AAAAAAAAHhzcQB+AAQAAAAEdwQAAAAKc3EAfgARQCQAAAAAAABzcQB+ABFAPgAAAAAAAHNxAH4AEUAkAAAAAAAAc3EAfgARAAAAAAAAAAB4c3EAfgAEAAAABHcEAAAACnNxAH4AET/gAAAAAAAAc3EAfgARP9MzMzMzMzNzcQB+ABEAAAAAAAAAAHNxAH4AET/wAAAAAAAAeHNxAH4ABAAAAAR3BAAAAApzcQB+ABE/4AAAAAAAAHNxAH4AET/JmZmZmZmac3EAfgARAAAAAAAAAABzcQB+ABE/8AAAAAAAAHhzcQB+AAQAAAAEdwQAAAAKc3EAfgARP+AAAAAAAABzcQB+ABE/0zMzMzMzM3NxAH4AEQAAAAAAAAAAc3EAfgARP/AAAAAAAAB4c3EAfgAEAAAABHcEAAAACnNxAH4AEQAAAAAAAAAAc3EAfgARAAAAAAAAAABzcQB+ABEAAAAAAAAAAHNxAH4AEQAAAAAAAAAAeHNxAH4ABAAAAAR3BAAAAApzcQB+ABEAAAAAAAAAAHNxAH4AEQAAAAAAAAAAc3EAfgARAAAAAAAAAABzcQB+ABEAAAAAAAAAAHhzcQB+AAQAAAAEdwQAAAAKc3EAfgARAAAAAAAAAABzcQB+ABEAAAAAAAAAAHNxAH4AEQAAAAAAAAAAc3EAfgARAAAAAAAAAAB4c3EAfgAEAAAABHcEAAAACnNxAH4AEQAAAAAAAAAAc3EAfgARAAAAAAAAAABzcQB+ABEAAAAAAAAAAHNxAH4AEQAAAAAAAAAAeHhzcQB+AAQAAAAJdwQAAAAKc3EAfgAEAAAAAncEAAAACnNxAH4AEUA4AAAAAAAAc3EAfgARQFZAAAAAAAB4c3EAfgAEAAAAAncEAAAACnNxAH4AEUAxAAAAAAAAc3EAfgARQBQAAAAAAAB4c3EAfgAEAAAAAncEAAAACnNxAH4AET/QAAAAAAAAc3EAfgARP+TMzMzMzM14c3EAfgAEAAAAAncEAAAACnNxAH4AET/XCj1wo9cKc3EAfgARP+3Cj1wo9cN4c3EAfgAEAAAAAncEAAAACnNxAH4AET/kzMzMzMzNc3EAfgARP9UeuFHrhR94c3EAfgAEAAAAAncEAAAACnNxAH4AEUDYdUAAAAAAc3EAfgARQO/0QAAAAAB4c3EAfgAEAAAAAncEAAAACnNxAH4AEUCAWAAAAAAAc3EAfgARQKP0AAAAAAB4c3EAfgAEAAAAAncEAAAACnNxAH4AEUCA8AAAAAAAc3EAfgARQIqwAAAAAAB4c3EAfgAEAAAAAncEAAAACnNxAH4AEUBJgAAAAAAAc3EAfgARQDkAAAAAAAB4eHQAImNvbS5pa29rb29uLnNlcmVuaXR5Lm1vZGVsLlByb2plY3Q=";
	protected static String packageBase64 = "rO0ABXNyACBjb20uaWtva29vbi5zZXJlbml0eS5tb2RlbC5Nb2RlbGSMpEB/c+h5AgAETAAGbGVnZW5kdAAQTGphdmEvdXRpbC9MaXN0O0wABmxpbWl0c3EAfgABTAAHbWV0cmljc3EAfgABTAAEbmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO3hwc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNpemV4cAAAAAl3BAAAAAp0AApDb3ZlcmFnZSAldAAKQ29tcGxleGl0eXQADkFic3RyYWN0IDwgMS4wdAAPU3RhYmlsaXR5IDwgMS4wdAAORGlzdGFuY2UgPCAxLjB0AAVMaW5lc3QACkludGVyZmFjZXN0AA9JbXBsZW1lbnRhdGlvbnN0AAhFeGVjdXRlZHhzcQB+AAQAAAAJdwQAAAAKc3EAfgAEAAAABHcEAAAACnNyABBqYXZhLmxhbmcuRG91YmxlgLPCSilr+wQCAAFEAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cEBJAAAAAAAAc3EAfgARQD4AAAAAAABzcQB+ABFAJAAAAAAAAHNxAH4AET/wAAAAAAAAeHNxAH4ABAAAAAR3BAAAAApzcQB+ABFAJAAAAAAAAHNxAH4AEUA+AAAAAAAAc3EAfgARQCQAAAAAAABzcQB+ABEAAAAAAAAAAHhzcQB+AAQAAAAEdwQAAAAKc3EAfgARP+AAAAAAAABzcQB+ABE/0zMzMzMzM3NxAH4AEQAAAAAAAAAAc3EAfgARP/AAAAAAAAB4c3EAfgAEAAAABHcEAAAACnNxAH4AET/gAAAAAAAAc3EAfgARP8mZmZmZmZpzcQB+ABEAAAAAAAAAAHNxAH4AET/wAAAAAAAAeHNxAH4ABAAAAAR3BAAAAApzcQB+ABE/4AAAAAAAAHNxAH4AET/TMzMzMzMzc3EAfgARAAAAAAAAAABzcQB+ABE/8AAAAAAAAHhzcQB+AAQAAAAEdwQAAAAKc3EAfgARAAAAAAAAAABzcQB+ABEAAAAAAAAAAHNxAH4AEQAAAAAAAAAAc3EAfgARAAAAAAAAAAB4c3EAfgAEAAAABHcEAAAACnNxAH4AEQAAAAAAAAAAc3EAfgARAAAAAAAAAABzcQB+ABEAAAAAAAAAAHNxAH4AEQAAAAAAAAAAeHNxAH4ABAAAAAR3BAAAAApzcQB+ABEAAAAAAAAAAHNxAH4AEQAAAAAAAAAAc3EAfgARAAAAAAAAAABzcQB+ABEAAAAAAAAAAHhzcQB+AAQAAAAEdwQAAAAKc3EAfgARAAAAAAAAAABzcQB+ABEAAAAAAAAAAHNxAH4AEQAAAAAAAAAAc3EAfgARAAAAAAAAAAB4eHNxAH4ABAAAAAl3BAAAAApzcQB+AAQAAAADdwQAAAAKc3EAfgARQCNrhR64UexzcQB+ABFAI2uFHrhR7HNxAH4AEUAja4UeuFHseHNxAH4ABAAAAAN3BAAAAApzcQB+ABFANKuFHrhR7HNxAH4AEUA0q4UeuFHsc3EAfgARQDSrhR64Uex4c3EAfgAEAAAAA3cEAAAACnNxAH4AET/B64UeuFHsc3EAfgARP8HrhR64UexzcQB+ABE/weuFHrhR7HhzcQB+AAQAAAADdwQAAAAKc3EAfgARP9hR64UeuFJzcQB+ABE/2FHrhR64UnNxAH4AET/YUeuFHrhSeHNxAH4ABAAAAAN3BAAAAApzcQB+ABE/1R64UeuFH3NxAH4AET/VHrhR64Ufc3EAfgARP9UeuFHrhR94c3EAfgAEAAAAA3cEAAAACnNxAH4AEUDDfYAAAAAAc3EAfgARQMN9gAAAAABzcQB+ABFAw32AAAAAAHhzcQB+AAQAAAADdwQAAAAKc3EAfgARQDsAAAAAAABzcQB+ABFAOwAAAAAAAHNxAH4AEUA7AAAAAAAAeHNxAH4ABAAAAAN3BAAAAApzcQB+ABFAY6AAAAAAAHNxAH4AEUBjoAAAAAAAc3EAfgARQGOgAAAAAAB4c3EAfgAEAAAAA3cEAAAACnNxAH4AEUD9zHAAAAAAc3EAfgARQP3McAAAAABzcQB+ABFA/cxwAAAAAHh4dAATZWR1LnVtZC5jcy5maW5kYnVncw==";
	protected static String classBase64 = "rO0ABXNyACBjb20uaWtva29vbi5zZXJlbml0eS5tb2RlbC5Nb2RlbGSMpEB/c+h5AgAETAAGbGVnZW5kdAAQTGphdmEvdXRpbC9MaXN0O0wABmxpbWl0c3EAfgABTAAHbWV0cmljc3EAfgABTAAEbmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO3hwc3IAE2phdmEudXRpbC5BcnJheUxpc3R4gdIdmcdhnQMAAUkABHNpemV4cAAAAAd3BAAAAAp0AApDb3ZlcmFnZSAldAAKQ29tcGxleGl0eXQAD1N0YWJpbGl0eSA8IDEuMHQABUxpbmVzdAAIRXhlY3V0ZWR0AAlFZmZlcmVuY2V0AAlBZmZlcmVuY2V4c3EAfgAEAAAAB3cEAAAACnNxAH4ABAAAAAR3BAAAAApzcgAQamF2YS5sYW5nLkRvdWJsZYCzwkopa/sEAgABRAAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHBASQAAAAAAAHNxAH4AD0A+AAAAAAAAc3EAfgAPQCQAAAAAAABzcQB+AA8/8AAAAAAAAHhzcQB+AAQAAAAEdwQAAAAKc3EAfgAPQCQAAAAAAABzcQB+AA9APgAAAAAAAHNxAH4AD0AkAAAAAAAAc3EAfgAPAAAAAAAAAAB4c3EAfgAEAAAABHcEAAAACnNxAH4ADz/gAAAAAAAAc3EAfgAPP8mZmZmZmZpzcQB+AA8AAAAAAAAAAHNxAH4ADz/wAAAAAAAAeHNxAH4ABAAAAAR3BAAAAApzcQB+AA8AAAAAAAAAAHNxAH4ADwAAAAAAAAAAc3EAfgAPAAAAAAAAAABzcQB+AA8AAAAAAAAAAHhzcQB+AAQAAAAEdwQAAAAKc3EAfgAPAAAAAAAAAABzcQB+AA8AAAAAAAAAAHNxAH4ADwAAAAAAAAAAc3EAfgAPAAAAAAAAAAB4c3EAfgAEAAAABHcEAAAACnNxAH4ADwAAAAAAAAAAc3EAfgAPAAAAAAAAAABzcQB+AA8AAAAAAAAAAHNxAH4ADwAAAAAAAAAAeHNxAH4ABAAAAAR3BAAAAApzcQB+AA8AAAAAAAAAAHNxAH4ADwAAAAAAAAAAc3EAfgAPAAAAAAAAAABzcQB+AA8AAAAAAAAAAHh4c3EAfgAEAAAAB3cEAAAACnNxAH4ABAAAAAN3BAAAAApzcQB+AA9AVW1wo9cKPXNxAH4AD0BVbXCj1wo9c3EAfgAPQFVtcKPXCj14c3EAfgAEAAAAA3cEAAAACnNxAH4ADz/vrhR64Ueuc3EAfgAPP++uFHrhR65zcQB+AA8/764UeuFHrnhzcQB+AAQAAAADdwQAAAAKc3EAfgAPP/AAAAAAAABzcQB+AA8/8AAAAAAAAHNxAH4ADz/wAAAAAAAAeHNxAH4ABAAAAAN3BAAAAApzcQB+AA9AHAAAAAAAAHNxAH4AD0AcAAAAAAAAc3EAfgAPQBwAAAAAAAB4c3EAfgAEAAAAA3cEAAAACnNxAH4AD0AYAAAAAAAAc3EAfgAPQBgAAAAAAABzcQB+AA9AGAAAAAAAAHhzcQB+AAQAAAADdwQAAAAKc3EAfgAPP/AAAAAAAABzcQB+AA8/8AAAAAAAAHNxAH4ADz/wAAAAAAAAeHNxAH4ABAAAAAN3BAAAAApzcQB+AA8AAAAAAAAAAHNxAH4ADwAAAAAAAAAAc3EAfgAPAAAAAAAAAAB4eHQAJGVkdS51bWQuY3MuZmluZGJ1Z3MuY2xhc3NmaWxlLkdsb2JhbA==";

	/**
	 * This generates a dummy model for testing and the initial data displayed rather than nothing.
	 * 
	 * @return a generated dummy model
	 */
	protected IModel getModel() {
		IModel model = (IModel) deserializeFromBase64(classBase64);
		return model;
	}
}
